services:
  database:
    image: postgres:17
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url
    volumes:
      - postgres:/data/postgres
volumes:
  postgres: