services:
  database:
    image: postgres:17
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url
    volumes:
      - postgres:/data/postgres
    networks:
      - shortNet
  api:
    container_name: back-end
    build: 
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - shortNet
volumes:
  postgres:
  
networks:
  shortNet:
    driver: bridge